services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: translation-api-play-code
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
